<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CompanyContact', 'doctrine');

/**
 * BaseCompanyContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $company_id
 * @property integer $usuario_id
 * 
 * @method integer        getId()         Returns the current record's "id" value
 * @method integer        getCompanyId()  Returns the current record's "company_id" value
 * @method integer        getUsuarioId()  Returns the current record's "usuario_id" value
 * @method CompanyContact setId()         Sets the current record's "id" value
 * @method CompanyContact setCompanyId()  Sets the current record's "company_id" value
 * @method CompanyContact setUsuarioId()  Sets the current record's "usuario_id" value
 * 
 * @package    samd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompanyContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('company_contact');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('company_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}