<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Registro', 'doctrine');

/**
 * BaseRegistro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $fecha_creacion
 * @property integer $cliente_id
 * @property timestamp $fecha_finalizacion
 * 
 * @method integer   getId()                 Returns the current record's "id" value
 * @method timestamp getFechaCreacion()      Returns the current record's "fecha_creacion" value
 * @method integer   getClienteId()          Returns the current record's "cliente_id" value
 * @method timestamp getFechaFinalizacion()  Returns the current record's "fecha_finalizacion" value
 * @method Registro  setId()                 Sets the current record's "id" value
 * @method Registro  setFechaCreacion()      Sets the current record's "fecha_creacion" value
 * @method Registro  setClienteId()          Sets the current record's "cliente_id" value
 * @method Registro  setFechaFinalizacion()  Sets the current record's "fecha_finalizacion" value
 * 
 * @package    samd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegistro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('registro');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha_creacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cliente_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_finalizacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}