<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Company', 'doctrine');

/**
 * BaseCompany
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $rif
 * @property string $nombre
 * @property integer $plan_id
 * @property integer $estatus_id
 * 
 * @method integer getRif()        Returns the current record's "rif" value
 * @method string  getNombre()     Returns the current record's "nombre" value
 * @method integer getPlanId()     Returns the current record's "plan_id" value
 * @method integer getEstatusId()  Returns the current record's "estatus_id" value
 * @method Company setRif()        Sets the current record's "rif" value
 * @method Company setNombre()     Sets the current record's "nombre" value
 * @method Company setPlanId()     Sets the current record's "plan_id" value
 * @method Company setEstatusId()  Sets the current record's "estatus_id" value
 * 
 * @package    samd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompany extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('company');
        $this->hasColumn('rif', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('plan_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('estatus_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}