<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UbicacionDolor', 'doctrine');

/**
 * BaseUbicacionDolor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $lugar_dolor_id
 * @property string $nombre
 * 
 * @method integer        getId()             Returns the current record's "id" value
 * @method integer        getLugarDolorId()   Returns the current record's "lugar_dolor_id" value
 * @method string         getNombre()         Returns the current record's "nombre" value
 * @method UbicacionDolor setId()             Sets the current record's "id" value
 * @method UbicacionDolor setLugarDolorId()   Sets the current record's "lugar_dolor_id" value
 * @method UbicacionDolor setNombre()         Sets the current record's "nombre" value
 * 
 * @package    samd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUbicacionDolor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ubicacion_dolor');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('lugar_dolor_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}