<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RecetaMedica', 'doctrine');

/**
 * BaseRecetaMedica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $fecha_inicio
 * @property string $medicamento
 * @property string $direccion
 * @property timestamp $fecha_fin
 * @property integer $vehiculo_id
 * @property integer $usuario_atm_id
 * 
 * @method integer      getId()             Returns the current record's "id" value
 * @method timestamp    getFechaInicio()    Returns the current record's "fecha_inicio" value
 * @method string       getMedicamento()    Returns the current record's "medicamento" value
 * @method string       getDireccion()      Returns the current record's "direccion" value
 * @method timestamp    getFechaFin()       Returns the current record's "fecha_fin" value
 * @method integer      getVehiculoId()     Returns the current record's "vehiculo_id" value
 * @method integer      getUsuarioAtmId()   Returns the current record's "usuario_atm_id" value
 * @method RecetaMedica setId()             Sets the current record's "id" value
 * @method RecetaMedica setFechaInicio()    Sets the current record's "fecha_inicio" value
 * @method RecetaMedica setMedicamento()    Sets the current record's "medicamento" value
 * @method RecetaMedica setDireccion()      Sets the current record's "direccion" value
 * @method RecetaMedica setFechaFin()       Sets the current record's "fecha_fin" value
 * @method RecetaMedica setVehiculoId()     Sets the current record's "vehiculo_id" value
 * @method RecetaMedica setUsuarioAtmId()   Sets the current record's "usuario_atm_id" value
 * 
 * @package    samd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRecetaMedica extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('receta_medica');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha_inicio', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('medicamento', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('direccion', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('fecha_fin', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('vehiculo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('usuario_atm_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}