<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatosTickets', 'doctrine');

/**
 * BaseDatosTickets
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $registro_id
 * @property timestamp $fecha_actualizacion
 * @property integer $metodo_solicitud_id
 * @property integer $usuario_atm_id
 * @property integer $sintoma_id
 * @property integer $estado_ticket_id
 * @property integer $prioridad_id
 * @property integer $foto_id
 * @property integer $firma_id
 * @property string $unidosis
 * @property integer $traslado_id
 * @property integer $receta_medica_id
 * 
 * @method integer      getId()                  Returns the current record's "id" value
 * @method integer      getRegistroId()          Returns the current record's "registro_id" value
 * @method timestamp    getFechaActualizacion()  Returns the current record's "fecha_actualizacion" value
 * @method integer      getMetodoSolicitudId()   Returns the current record's "metodo_solicitud_id" value
 * @method integer      getUsuarioAtmId()        Returns the current record's "usuario_atm_id" value
 * @method integer      getSintomaId()           Returns the current record's "sintoma_id" value
 * @method integer      getEstadoTicketId()      Returns the current record's "estado_ticket_id" value
 * @method integer      getPrioridadId()         Returns the current record's "prioridad_id" value
 * @method integer      getFotoId()              Returns the current record's "foto_id" value
 * @method integer      getFirmaId()             Returns the current record's "firma_id" value
 * @method string       getUnidosis()            Returns the current record's "unidosis" value
 * @method integer      getTrasladoId()          Returns the current record's "traslado_id" value
 * @method integer      getRecetaMedicaId()      Returns the current record's "receta_medica_id" value
 * @method DatosTickets setId()                  Sets the current record's "id" value
 * @method DatosTickets setRegistroId()          Sets the current record's "registro_id" value
 * @method DatosTickets setFechaActualizacion()  Sets the current record's "fecha_actualizacion" value
 * @method DatosTickets setMetodoSolicitudId()   Sets the current record's "metodo_solicitud_id" value
 * @method DatosTickets setUsuarioAtmId()        Sets the current record's "usuario_atm_id" value
 * @method DatosTickets setSintomaId()           Sets the current record's "sintoma_id" value
 * @method DatosTickets setEstadoTicketId()      Sets the current record's "estado_ticket_id" value
 * @method DatosTickets setPrioridadId()         Sets the current record's "prioridad_id" value
 * @method DatosTickets setFotoId()              Sets the current record's "foto_id" value
 * @method DatosTickets setFirmaId()             Sets the current record's "firma_id" value
 * @method DatosTickets setUnidosis()            Sets the current record's "unidosis" value
 * @method DatosTickets setTrasladoId()          Sets the current record's "traslado_id" value
 * @method DatosTickets setRecetaMedicaId()      Sets the current record's "receta_medica_id" value
 * 
 * @package    samd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDatosTickets extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('datos_tickets');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('registro_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_actualizacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('metodo_solicitud_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('usuario_atm_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('sintoma_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('estado_ticket_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('prioridad_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('foto_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('firma_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('unidosis', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('traslado_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('receta_medica_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}