<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LugarDolor', 'doctrine');

/**
 * BaseLugarDolor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $motivo_id
 * @property string $nombre
 * 
 * @method integer    getId()        Returns the current record's "id" value
 * @method integer    getMotivoId()  Returns the current record's "motivo_id" value
 * @method string     getNombre()    Returns the current record's "nombre" value
 * @method LugarDolor setId()        Sets the current record's "id" value
 * @method LugarDolor setMotivoId()  Sets the current record's "motivo_id" value
 * @method LugarDolor setNombre()    Sets the current record's "nombre" value
 * 
 * @package    samd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLugarDolor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lugar_dolor');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('motivo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}