<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Sintomas', 'doctrine');

/**
 * BaseSintomas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $ubicacion_dolor_id
 * @property string $descripcion
 * @property integer $frecuencia
 * @property integer $intensidad
 * @property string $inicio_sintoma
 * @property string $sintomas_asociados
 * @property string $comentarios
 * @property string $adicionales
 * 
 * @method integer  getId()                 Returns the current record's "id" value
 * @method integer  getUbicacionDolorId()   Returns the current record's "ubicacion_dolor_id" value
 * @method string   getDescripcion()        Returns the current record's "descripcion" value
 * @method integer  getFrecuencia()         Returns the current record's "frecuencia" value
 * @method integer  getIntensidad()         Returns the current record's "intensidad" value
 * @method string   getInicioSintoma()      Returns the current record's "inicio_sintoma" value
 * @method string   getSintomasAsociados()  Returns the current record's "sintomas_asociados" value
 * @method string   getComentarios()        Returns the current record's "comentarios" value
 * @method string   getAdicionales()        Returns the current record's "adicionales" value
 * @method Sintomas setId()                 Sets the current record's "id" value
 * @method Sintomas setUbicacionDolorId()   Sets the current record's "ubicacion_dolor_id" value
 * @method Sintomas setDescripcion()        Sets the current record's "descripcion" value
 * @method Sintomas setFrecuencia()         Sets the current record's "frecuencia" value
 * @method Sintomas setIntensidad()         Sets the current record's "intensidad" value
 * @method Sintomas setInicioSintoma()      Sets the current record's "inicio_sintoma" value
 * @method Sintomas setSintomasAsociados()  Sets the current record's "sintomas_asociados" value
 * @method Sintomas setComentarios()        Sets the current record's "comentarios" value
 * @method Sintomas setAdicionales()        Sets the current record's "adicionales" value
 * 
 * @package    samd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSintomas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sintomas');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('ubicacion_dolor_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('frecuencia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('intensidad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('inicio_sintoma', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('sintomas_asociados', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('comentarios', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 500,
             ));
        $this->hasColumn('adicionales', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}