<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Plan', 'doctrine');

/**
 * BasePlan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $caracteristicas
 * 
 * @method integer getId()              Returns the current record's "id" value
 * @method string  getNombre()          Returns the current record's "nombre" value
 * @method string  getCaracteristicas() Returns the current record's "caracteristicas" value
 * @method Plan    setId()              Sets the current record's "id" value
 * @method Plan    setNombre()          Sets the current record's "nombre" value
 * @method Plan    setCaracteristicas() Sets the current record's "caracteristicas" value
 * 
 * @package    samd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('plan');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('caracteristicas', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}