<?php

/**
 * DatosContactosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DatosContactosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DatosContactosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DatosContactos');
    }
}