<?php

/**
 * DatosTicketsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DatosTicketsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DatosTicketsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DatosTickets');
    }
}