<?php

/**
 * DependenciaFamiliarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DependenciaFamiliarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DependenciaFamiliarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DependenciaFamiliar');
    }
}