<?php

/**
 * EstatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estatus');
    }
}