<?php

/**
 * FirmaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FirmaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FirmaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Firma');
    }
}