<?php

/**
 * LugarDolorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LugarDolorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LugarDolorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LugarDolor');
    }
}