<?php

/**
 * MetodoSolicitudTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MetodoSolicitudTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MetodoSolicitudTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MetodoSolicitud');
    }
}