<?php

/**
 * MotivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MotivoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MotivoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Motivo');
    }
}