<?php

/**
 * RecetaMedicaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RecetaMedicaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RecetaMedicaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RecetaMedica');
    }
}