<?php

/**
 * SintomasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SintomasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SintomasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sintomas');
    }
}