<?php

/**
 * UbicacionDolorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UbicacionDolorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UbicacionDolorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UbicacionDolor');
    }
}