<?php

/**
 * UnidadesVehicularesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnidadesVehicularesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnidadesVehicularesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UnidadesVehiculares');
    }
}