Company:
  connection: doctrine
  tableName: company
  columns:
    rif:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    nombre:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    plan_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    estatus_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
CompanyContact:
  connection: doctrine
  tableName: company_contact
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    company_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    usuario_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
DatosContactos:
  connection: doctrine
  tableName: datos_contactos
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    company_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    usuario_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    direccion_principal:
      type: string(500)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    direccion_2:
      type: string(500)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    telefono_principal:
      type: string(11)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    telefono_2:
      type: string(11)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    telefono_3:
      type: string(11)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    email_principal:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    email_2:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    email_3:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
DatosTickets:
  connection: doctrine
  tableName: datos_tickets
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    registro_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    fecha_actualizacion:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    metodo_solicitud_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    usuario_atm_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    sintoma_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    estado_ticket_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    prioridad_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    foto_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    firma_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    unidosis:
      type: string(500)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    traslado_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    receta_medica_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
DependenciaFamiliar:
  connection: doctrine
  tableName: dependencia_familiar
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    titular_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    anexo_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
EstadoTicket:
  connection: doctrine
  tableName: estado_ticket
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Estatus:
  connection: doctrine
  tableName: estatus
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Firma:
  connection: doctrine
  tableName: firma
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(150)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Foto:
  connection: doctrine
  tableName: foto
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(150)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
LugarDolor:
  connection: doctrine
  tableName: lugar_dolor
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    motivo_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    nombre:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
MetodoSolicitud:
  connection: doctrine
  tableName: metodo_solicitud
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Motivo:
  connection: doctrine
  tableName: motivo
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Plan:
  connection: doctrine
  tableName: plan
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    caracteristicas:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Prioridad:
  connection: doctrine
  tableName: prioridad
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
RecetaMedica:
  connection: doctrine
  tableName: receta_medica
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    fecha_inicio:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    medicamento:
      type: string(500)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    direccion:
      type: string(500)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha_fin:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    vehiculo_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    usuario_atm_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
Registro:
  connection: doctrine
  tableName: registro
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    fecha_creacion:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    cliente_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    fecha_finalizacion:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
Roles:
  connection: doctrine
  tableName: roles
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Sintomas:
  connection: doctrine
  tableName: sintomas
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    ubicacion_dolor_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    descripcion:
      type: string(150)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    frecuencia:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    intensidad:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    inicio_sintoma:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    sintomas_asociados:
      type: string(500)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    comentarios:
      type: string(500)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    adicionales:
      type: string(500)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
Traslado:
  connection: doctrine
  tableName: traslado
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    fecha_inicio:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    direccion:
      type: string(500)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha_fin:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    vehiculo_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    usuario_atm_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
UbicacionDolor:
  connection: doctrine
  tableName: ubicacion_dolor
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    lugar_dolor_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    nombre:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
UnidadesVehiculares:
  connection: doctrine
  tableName: unidades_vehiculares
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(250)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Usuarios:
  connection: doctrine
  tableName: usuarios
  columns:
    cedula:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    nombre:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    apellido:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha_nac:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    username:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    password:
      type: string(150)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    company_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    rol_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
